version: "3.1"
services:
  frontend:
    image: beta/frontend:latest
    container_name: frontend
    ports:
      - 80:80
      - 443:443
    networks:
      - cmplr
    restart: on-failure
    depends_on:
      - backend

  backend:
    image: beta/backend:latest
    container_name: backend
    networks:
      - cmplr
    depends_on:
      - db
    restart: on-failure
    volumes:
      - ./docker-compose/backend.log:/var/www/storage/logs/laravel.log

  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DATABASE: ${DB_DATABASE}
      POSTGRES_ROOT_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: pgsql
    ports:
      - 3306:5432
    volumes:
      - ./docker-compose/pgsql:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    networks:
      - cmplr
networks:
  cmplr:
    driver: bridge
volumes:
  postgres-data:
  backend-logs:
