version: "2.0"
services:
  node_exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - 9100:9100
    command:
      - "--path.rootfs=/host"
    volumes:
      - "/:/host:ro,rslave"
    pid: host
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    restart: always
